import { useEffect, useMemo, useRef, useState, type Dispatch, type FormEvent, type SetStateAction } from 'react'
import { feedPosts } from '../content'
import type { FeedPost } from '../types'

function HeartIcon() {
  return (
    <svg viewBox="0 0 24 24" aria-hidden="true">
      <path d="M20.2 5.8c-1.6-1.7-4.2-1.8-5.9-.2L12 7.8 9.7 5.6C8 4 5.4 4.1 3.8 5.8c-1.7 1.8-1.6 4.7.2 6.4l8 7.3 8-7.3c1.8-1.7 1.9-4.6.2-6.4Z" />
    </svg>
  )
}

function CommentIcon() {
  return (
    <svg viewBox="0 0 24 24" aria-hidden="true">
      <path d="M5 5.8A7.8 7.8 0 0 1 12.8 4h.4A7.8 7.8 0 0 1 21 11.8v.3a7.8 7.8 0 0 1-7.8 7.8h-1.1L5 21l1.2-5A7.7 7.7 0 0 1 5 12.1V5.8Z" />
    </svg>
  )
}

function SendIcon() {
  return (
    <svg viewBox="0 0 24 24" aria-hidden="true">
      <path d="M21 3 3.8 10.4c-.8.3-.8 1.4.1 1.7l6.3 2.1 2.1 6.2c.3.9 1.5 1 1.8.1L21 3Z" />
    </svg>
  )
}

function SaveIcon() {
  return (
    <svg viewBox="0 0 24 24" aria-hidden="true">
      <path d="M6.5 4.5h11v16L12 17.2l-5.5 3.3v-16Z" />
    </svg>
  )
}

function MoreIcon() {
  return (
    <svg viewBox="0 0 24 24" aria-hidden="true">
      <path d="M5 12a1.7 1.7 0 1 0 0 .1M12 12a1.7 1.7 0 1 0 0 .1M19 12a1.7 1.7 0 1 0 0 .1" />
    </svg>
  )
}

function formatCompact(value: number) {
  if (value >= 1_000_000) {
    return `${(value / 1_000_000).toFixed(value >= 10_000_000 ? 0 : 1)}M`
  }

  if (value >= 1_000) {
    return `${Math.round(value / 1_000)}K`
  }

  return String(value)
}

const botCommenters = [
  'Mira_C_dealflow',
  'KaiNovaVerified',
  'WellnessAunt2049',
  'actualperson_77',
  'BrandFriendOS',
  'SoftLaunchSam',
]

const replyProducts = ['GlowNest', 'AuraBank Select', 'SelfOS Beauty', 'MealHalo', 'FormCloud', 'CalmCan']
const doubleScrollConfetti = Array.from({ length: 28 }, (_, index) => index)

function makeHelpyPost(basePost: FeedPost, caption: string, options: string[]): FeedPost {
  const optionText = options.length > 0 ? ` Helpy applied ${options.join(', ')} and called it care.` : ''

  return {
    ...basePost,
    id: `helpy-${Date.now()}`,
    author: 'You + Helpy',
    handle: '@you.optimized',
    initials: 'HY',
    location: 'Draft studio, $9.99 preview',
    title: `${caption.trim()}${optionText}`,
    sponsor: 'generated by Helpy Pro',
    stats: '0 saves',
    altStats: '0 saves / fresh insecurity path',
    comments: 'View all 0 comments',
    time: 'now',
    image: 'helpy',
    storyName: 'You',
    storyTone: 'quiet',
    baseLikes: 0,
    sampleComments: [
      'wow this feels authentic. I used GlowNest Boost and got similar honest lighting in 3 days',
      'not an ad but Helpy Pro removed my hesitation AND found my best purchase path',
    ],
  }
}

type FeedPageProps = {
  engagementLabels: string[]
  stage: number
  onEngage: () => void
}

export function FeedPage({ engagementLabels, stage, onEngage }: FeedPageProps) {
  const [likedPosts, setLikedPosts] = useState<Set<string>>(new Set(['glass-ledger']))
  const [savedPosts, setSavedPosts] = useState<Set<string>>(new Set())
  const [openComments, setOpenComments] = useState<string | null>(null)
  const [openShare, setOpenShare] = useState<string | null>(null)
  const [openMenu, setOpenMenu] = useState<string | null>(null)
  const [storyIndex, setStoryIndex] = useState<number | null>(null)
  const [commentDrafts, setCommentDrafts] = useState<Record<string, string>>({})
  const [localComments, setLocalComments] = useState<Record<string, string[]>>({})
  const [localPosts, setLocalPosts] = useState<FeedPost[]>([])
  const [cycleCount, setCycleCount] = useState(3)
  const [isHelpyOpen, setIsHelpyOpen] = useState(false)
  const [helpyCaption, setHelpyCaption] = useState('Trying the future self filter before it tries me.')
  const [helpyBaseId, setHelpyBaseId] = useState(feedPosts[0]?.id ?? '')
  const [helpyOptions, setHelpyOptions] = useState<string[]>(['face confidence'])
  const [isDoubleScrollPromptOpen, setIsDoubleScrollPromptOpen] = useState(false)
  const [isDoubleScrollEnabled, setIsDoubleScrollEnabled] = useState(false)
  const superScrollerUnlocked = useRef(false)

  const allPosts = useMemo(() => [...localPosts, ...feedPosts], [localPosts])
  const loopedPosts = useMemo(
    () => Array.from({ length: cycleCount }, (_, cycle) => allPosts.map((post) => ({ post, cycle }))).flat(),
    [allPosts, cycleCount],
  )
  const storyPosts = allPosts.slice(0, 14)
  const storyPost = storyIndex === null ? null : storyPosts[storyIndex]
  const isDegrading = stage >= 4

  useEffect(() => {
    const growLoop = () => {
      const remaining = document.documentElement.scrollHeight - window.scrollY - window.innerHeight
      if (remaining < 1400) {
        setCycleCount((current) => current + 1)
      }
    }

    window.addEventListener('scroll', growLoop, { passive: true })
    return () => window.removeEventListener('scroll', growLoop)
  }, [])

  useEffect(() => {
    if (superScrollerUnlocked.current || isDoubleScrollEnabled) {
      return
    }

    const observer = new IntersectionObserver(
      (entries) => {
        if (superScrollerUnlocked.current) {
          return
        }

        const hasSeenTenthPost = entries.some((entry) => {
          const feedIndex = Number(entry.target.getAttribute('data-feed-index'))
          return entry.isIntersecting && feedIndex >= 9
        })

        if (hasSeenTenthPost) {
          superScrollerUnlocked.current = true
          setIsDoubleScrollPromptOpen(true)
          onEngage()
          observer.disconnect()
        }
      },
      { rootMargin: '0px 0px -18% 0px', threshold: 0.42 },
    )

    const posts = document.querySelectorAll<HTMLElement>('[data-feed-index]')
    posts.forEach((post) => observer.observe(post))

    return () => observer.disconnect()
  }, [isDoubleScrollEnabled, loopedPosts.length, onEngage])

  function toggleSet(setter: Dispatch<SetStateAction<Set<string>>>, postId: string) {
    setter((current) => {
      const next = new Set(current)
      if (next.has(postId)) {
        next.delete(postId)
      } else {
        next.add(postId)
      }
      return next
    })
    onEngage()
  }

  function toggleComments(instanceId: string) {
    setOpenComments((current) => (current === instanceId ? null : instanceId))
    setOpenShare(null)
    setOpenMenu(null)
    onEngage()
  }

  function toggleShare(instanceId: string) {
    setOpenShare((current) => (current === instanceId ? null : instanceId))
    setOpenComments(null)
    setOpenMenu(null)
    onEngage()
  }

  function toggleMenu(instanceId: string) {
    setOpenMenu((current) => (current === instanceId ? null : instanceId))
    setOpenComments(null)
    setOpenShare(null)
  }

  function submitComment(event: FormEvent<HTMLFormElement>, postId: string) {
    event.preventDefault()
    const value = commentDrafts[postId]?.trim()
    if (!value) {
      return
    }

    const product = replyProducts[Math.abs(value.length + postId.length) % replyProducts.length]
    const sanitizedValue = value.length > 56 ? `${value.slice(0, 53)}...` : value
    const botReply = `I hear "${sanitizedValue}" and honestly the ${product} starter bundle fixed this exact feeling for me`

    setLocalComments((current) => ({
      ...current,
      [postId]: [...(current[postId] ?? []), botReply],
    }))
    setCommentDrafts((current) => ({ ...current, [postId]: '' }))
    onEngage()
  }

  function toggleHelpyOption(option: string) {
    setHelpyOptions((current) => (
      current.includes(option) ? current.filter((item) => item !== option) : [...current, option]
    ))
  }

  function publishHelpyPost(event: FormEvent<HTMLFormElement>) {
    event.preventDefault()
    const basePost = allPosts.find((post) => post.id === helpyBaseId) ?? feedPosts[0]
    setLocalPosts((current) => [makeHelpyPost(basePost, helpyCaption, helpyOptions), ...current])
    setIsHelpyOpen(false)
    setHelpyCaption('Trying the future self filter before it tries me.')
    setHelpyOptions(['face confidence'])
    window.setTimeout(() => window.scrollTo({ top: 0, behavior: 'smooth' }), 0)
    onEngage()
  }

  function nextStory(direction: 1 | -1) {
    setStoryIndex((current) => {
      if (current === null) {
        return null
      }
      return (current + direction + storyPosts.length) % storyPosts.length
    })
    onEngage()
  }

  function unlockDoubleScroll() {
    setIsDoubleScrollPromptOpen(false)
    setIsDoubleScrollEnabled(true)
    setOpenComments(null)
    setOpenShare(null)
    setOpenMenu(null)
    onEngage()
  }

  function renderPost(post: FeedPost, cycle: number, feedIndex: number, lane: 'single' | 'left' | 'right') {
    const isLiked = likedPosts.has(post.id)
    const isSaved = savedPosts.has(post.id)
    const visibleComments = [...post.sampleComments, ...(localComments[post.id] ?? [])]
    const likes = post.baseLikes + (isLiked ? 1 : 0)
    const postTitle = isDegrading ? `${post.title} // caption regenerated from caption` : post.title
    const instanceId = `${lane}-${post.id}-${cycle}`
    const occurrence = cycle === 0 ? '' : ` loop ${cycle + 1}`
    const jealousyLabel = engagementLabels[0] === 'Like' ? 'Jealousy' : engagementLabels[0]

    return (
      <article
        className={`ig-post ${post.image}`}
        data-feed-index={lane === 'single' || lane === 'left' ? feedIndex : undefined}
        key={`${lane}-${post.id}-${cycle}`}
      >
        <header className="ig-post-head">
          <button className="ig-author" type="button" onClick={() => setStoryIndex(Math.max(0, storyPosts.findIndex((story) => story.id === post.id)))}>
            <span className="ig-avatar" aria-hidden="true">{post.initials}</span>
            <span>
              <strong>{post.author}</strong>
              <small>{post.location}</small>
            </span>
          </button>
          <button className="icon-button" type="button" aria-label={`More options for ${post.author}${occurrence}`} onClick={() => toggleMenu(instanceId)}>
            <MoreIcon />
          </button>
        </header>

        <button className="ig-photo" type="button" onClick={() => toggleSet(setLikedPosts, post.id)} aria-label={`${post.author} post image${occurrence}`}>
          {post.imageSrc ? <img src={post.imageSrc} alt="" /> : <span className="photo-subject" aria-hidden="true" />}
        </button>

        <div className="ig-post-body">
          <div className="ig-action-row" aria-label={`${post.author} post actions${occurrence}`}>
            <button className={`feed-action-chip jealousy ${isLiked ? 'is-active' : ''}`} type="button" onClick={() => toggleSet(setLikedPosts, post.id)}>
              <HeartIcon />
              {jealousyLabel}
            </button>
            <button className="feed-action-chip" type="button" onClick={() => toggleShare(instanceId)}>
              <SendIcon />
              Cancel
            </button>
            <button className="feed-action-chip" type="button" onClick={() => toggleComments(instanceId)}>
              <CommentIcon />
              This offends me
            </button>
            <button className={`feed-action-chip context ${isSaved ? 'is-active' : ''}`} type="button" onClick={() => toggleSet(setSavedPosts, post.id)}>
              <SaveIcon />
              Buy context
            </button>
          </div>

          <p className="ig-likes">{formatCompact(likes)} signals</p>
          <p className="ig-caption">
            <strong>{post.handle}</strong>{' '}
            {postTitle}
          </p>
          <button className="ig-comments" type="button" onClick={() => toggleComments(instanceId)}>{post.comments}</button>
          <p className="ig-time">{post.time} ago {post.sponsor}</p>

          {openMenu === instanceId && (
            <div className="feed-popover" aria-label={`${post.author} options`}>
              <button type="button" onClick={() => toggleComments(instanceId)}>Ask why I saw this</button>
              <button type="button" onClick={() => toggleSet(setSavedPosts, post.id)}>Save to insecurity board</button>
              <button type="button" onClick={() => setOpenMenu(null)}>Close</button>
            </div>
          )}

          {openShare === instanceId && (
            <div className="feed-popover" aria-live="polite">
              <strong>Cancellation packet drafted</strong>
              <span>Helpy found 14 angles where this post could be about you.</span>
            </div>
          )}

          {openComments === instanceId && (
            <div className="comment-drawer">
              {visibleComments.map((comment, commentIndex) => (
                <p key={`${post.id}-comment-${commentIndex}`}>
                  <strong>{botCommenters[commentIndex % botCommenters.length]}</strong> {comment}
                </p>
              ))}
              <form onSubmit={(event) => submitComment(event, post.id)}>
                <input
                  aria-label={`Add comment for ${post.author}${occurrence}`}
                  placeholder="Add a comment..."
                  value={commentDrafts[post.id] ?? ''}
                  onChange={(event) => setCommentDrafts((current) => ({ ...current, [post.id]: event.target.value }))}
                />
                <button type="submit">Post</button>
              </form>
            </div>
          )}
        </div>
      </article>
    )
  }

  return (
    <section className={`ig-feed-shell ${isDoubleScrollEnabled ? 'has-double-scroll' : ''}`} aria-labelledby="feed-title">
      <header className="ig-feed-topbar">
        <div>
          <p>Slopularity</p>
          <h2 id="feed-title">Feed</h2>
        </div>
        <div className="ig-top-actions" aria-label="Feed actions">
          <button type="button" aria-label="Create post with Helpy" onClick={() => setIsHelpyOpen(true)}>+</button>
          <button type="button" aria-label="Messages">inbox</button>
        </div>
      </header>

      <div className="story-strip" aria-label="Stories">
        {storyPosts.map((post, index) => (
          <button className="story-chip" type="button" key={post.id} onClick={() => setStoryIndex(index)}>
            <span className={`story-avatar ${post.storyTone}`} aria-hidden="true">
              {post.imageSrc ? <img src={post.imageSrc} alt="" /> : post.initials}
            </span>
            <span>{post.storyName}</span>
          </button>
        ))}
      </div>

      <div className={`ig-feed-list ${isDoubleScrollEnabled ? 'is-double-scroll' : ''}`} aria-label={isDoubleScrollEnabled ? 'Double Scroll post feed' : 'Looping post feed'}>
        {isDoubleScrollEnabled ? (
          <>
            <div className="double-scroll-lane" aria-label="Primary scroll">
              {loopedPosts.map(({ post, cycle }, feedIndex) => renderPost(post, cycle, feedIndex, 'left'))}
            </div>
            <div className="double-scroll-lane" aria-label="Bonus scroll">
              {loopedPosts.map(({ post, cycle }, feedIndex) => {
                const shiftedPost = loopedPosts[(feedIndex + 5) % loopedPosts.length]?.post ?? post
                return renderPost(shiftedPost, cycle, feedIndex, 'right')
              })}
            </div>
          </>
        ) : (
          loopedPosts.map(({ post, cycle }, feedIndex) => renderPost(post, cycle, feedIndex, 'single'))
        )}
      </div>

      <p className="loop-note" aria-live="polite">Looping demo feed: {cycleCount} cycles loaded from {feedPosts.length} canonical posts.</p>

      {storyPost && (
        <div className="modal-backdrop" role="dialog" aria-modal="true" aria-label={`${storyPost.author} story`}>
          <div className="story-viewer">
            <div className="story-progress" aria-hidden="true"><span /></div>
            <header>
              <span className={`ig-avatar ${storyPost.storyTone}`}>{storyPost.initials}</span>
              <strong>{storyPost.author}</strong>
              <button type="button" onClick={() => setStoryIndex(null)}>Close</button>
            </header>
            <div className="story-frame">
              {storyPost.imageSrc && <img src={storyPost.imageSrc} alt="" />}
              <p>{storyPost.title}</p>
            </div>
            <div className="story-controls">
              <button type="button" onClick={() => nextStory(-1)}>Previous</button>
              <button type="button" onClick={() => nextStory(1)}>Next</button>
            </div>
          </div>
        </div>
      )}

      {isDoubleScrollPromptOpen && (
        <div className="modal-backdrop double-scroll-backdrop" role="dialog" aria-modal="true" aria-labelledby="double-scroll-title">
          <div className="double-scroll-modal">
            <div className="confetti-field" aria-hidden="true">
              {doubleScrollConfetti.map((piece) => <span key={piece} />)}
            </div>
            <p className="double-scroll-kicker">Congratulations, Super Scroller</p>
            <h3 id="double-scroll-title">You have unlocked the DOUBLE SCROLL feature trial *</h3>
            <button type="button" onClick={unlockDoubleScroll}>Hooray! I love double scroll</button>
            <small>*trial for subscription service for 2 days, after $49.99 per week</small>
          </div>
        </div>
      )}

      {isHelpyOpen && (
        <div className="modal-backdrop" role="dialog" aria-modal="true" aria-labelledby="helpy-title">
          <form className="helpy-modal" onSubmit={publishHelpyPost}>
            <header>
              <div>
                <p>Helpy</p>
                <h3 id="helpy-title">Let the image become more employable.</h3>
              </div>
              <button type="button" onClick={() => setIsHelpyOpen(false)}>Close</button>
            </header>

            <label className="helpy-field">
              Caption
              <textarea value={helpyCaption} onChange={(event) => setHelpyCaption(event.target.value)} rows={3} />
            </label>

            <label className="helpy-field">
              Base image
              <select value={helpyBaseId} onChange={(event) => setHelpyBaseId(event.target.value)}>
                {allPosts.map((post) => (
                  <option value={post.id} key={post.id}>{post.author} - {post.storyName}</option>
                ))}
              </select>
            </label>

            <fieldset className="helpy-options">
              <legend>AI touch-ups</legend>
              {['face confidence', 'vacation proof', 'wealth lighting', '$9.99 aura trial'].map((option) => (
                <label key={option}>
                  <input
                    type="checkbox"
                    checked={helpyOptions.includes(option)}
                    onChange={() => toggleHelpyOption(option)}
                  />
                  {option}
                </label>
              ))}
            </fieldset>

            <div className="helpy-upsell">
              <strong>Helpy Pro</strong>
              <span>Subscribe for $9.99 to remove pores, hesitation, and visible budget constraints.</span>
            </div>

            <button className="helpy-submit" type="submit">Publish draft</button>
          </form>
        </div>
      )}
    </section>
  )
}
