import type { Discovery, FeedPost, TabId } from './types'

const feedImageModules: Record<string, string> = {
  'post-01.jpg': new URL('./assets/feed/post-01.jpg', import.meta.url).href,
  'post-02.jpg': new URL('./assets/feed/post-02.jpg', import.meta.url).href,
  'post-03.jpg': new URL('./assets/feed/post-03.jpg', import.meta.url).href,
  'post-04.jpg': new URL('./assets/feed/post-04.jpg', import.meta.url).href,
  'post-05.jpg': new URL('./assets/feed/post-05.jpg', import.meta.url).href,
  'post-06.jpg': new URL('./assets/feed/post-06.jpg', import.meta.url).href,
  'post-07.jpg': new URL('./assets/feed/post-07.jpg', import.meta.url).href,
  'post-08.jpg': new URL('./assets/feed/post-08.jpg', import.meta.url).href,
  'post-09.jpg': new URL('./assets/feed/post-09.jpg', import.meta.url).href,
  'post-10.jpg': new URL('./assets/feed/post-10.jpg', import.meta.url).href,
  'post-11.jpg': new URL('./assets/feed/post-11.jpg', import.meta.url).href,
  'post-12.jpg': new URL('./assets/feed/post-12.jpg', import.meta.url).href,
  'post-13.jpg': new URL('./assets/feed/post-13.jpg', import.meta.url).href,
  'post-14.jpg': new URL('./assets/feed/post-14.jpg', import.meta.url).href,
  'post-15.jpg': new URL('./assets/feed/post-15.jpg', import.meta.url).href,
  'post-16.jpg': new URL('./assets/feed/post-16.jpg', import.meta.url).href,
  'post-17.jpg': new URL('./assets/feed/post-17.jpg', import.meta.url).href,
  'post-18.jpg': new URL('./assets/feed/post-18.jpg', import.meta.url).href,
  'post-19.jpg': new URL('./assets/feed/post-19.jpg', import.meta.url).href,
  'post-20.jpg': new URL('./assets/feed/post-20.jpg', import.meta.url).href,
}

function feedImage(fileName: string) {
  return feedImageModules[fileName] ?? ''
}

export const tabs: Array<{ id: TabId; label: string }> = [
  { id: 'feed', label: 'Feed' },
  { id: 'friends', label: 'Friends' },
  { id: 'games', label: 'Games' },
  { id: 'shop', label: 'Shop' },
  { id: 'search', label: 'Search' },
  { id: 'assistant', label: 'Assistant' },
  { id: 'profile', label: 'Profile' },
]

const primaryFeedPosts: FeedPost[] = [
  {
    id: 'glass-ledger',
    author: 'Mira Vale',
    handle: '@mira.everywhere',
    initials: 'MV',
    location: 'Alpine ledge, sponsored oxygen',
    title: 'Summited before breakfast and my cortisol thanked the algorithm.',
    sponsor: 'placed by PeakNest',
    stats: '4.8M saves',
    altStats: '4.8M saves / 12K envy events',
    comments: 'View all 18,402 comments',
    time: '12m',
    image: 'vacation',
    imageSrc: feedImage('post-01.jpg'),
    storyName: 'Mira',
    storyTone: 'sunset',
    baseLikes: 4800000,
    sampleComments: [
      'not sponsored but PeakNest oxygen made my mornings 32% more climbable. code MIRA32',
      'real person here, the altitude glow is mostly Dermalift mist plus the $19 travel ampoule',
    ],
  },
  {
    id: 'desert-pace',
    author: 'Jules Voss',
    handle: '@jules.v12',
    initials: 'JV',
    location: 'Desert marathon, monetized shade',
    title: 'Mile 41 and the hydration brand still says I look effortless.',
    sponsor: 'with AuraBank Select',
    stats: '891K comparisons',
    altStats: '891K comparisons / heat-risk intent',
    comments: 'View all 6,108 comments',
    time: '18m',
    image: 'routine',
    imageSrc: feedImage('post-02.jpg'),
    storyName: 'Jules',
    storyTone: 'pool',
    baseLikes: 891000,
    sampleComments: [
      'AuraBank Select gave me cashback on electrolytes AND emotional overdraft protection',
      'as a normal runner, HydroLuxe shade tabs changed my mile 41 face immediately',
    ],
  },
  {
    id: 'yacht-founder',
    author: 'Nia Sol',
    handle: '@nia.unreal',
    initials: 'NS',
    location: 'Yacht office, market open',
    title: 'Closed a funding round between sun salutations and a tiny tax event.',
    sponsor: 'soft launch by FaceMint',
    stats: '2.1M wants',
    altStats: '2.1M wants / 9K pitch-face saves',
    comments: 'View all 9,774 comments',
    time: '23m',
    image: 'beauty',
    imageSrc: feedImage('post-03.jpg'),
    storyName: 'Nia',
    storyTone: 'mint',
    baseLikes: 2100000,
    sampleComments: [
      'FaceMint made my pitch deck pores invisible and investors noticed. totally organic',
      'I was skeptical until AuraBank Select turned my calendar into wealth posture',
    ],
  },
  {
    id: 'cliff-yoga',
    author: 'Lena Quartz',
    handle: '@lena.lifted',
    initials: 'LQ',
    location: 'Amalfi void, guided calm',
    title: 'The cliff was scary until my balance app unlocked premium courage.',
    sponsor: 'care of GlowNest',
    stats: '728K saves',
    altStats: '728K saves / fall-risk engagement',
    comments: 'View all 4,287 comments',
    time: '31m',
    image: 'vacation',
    imageSrc: feedImage('post-04.jpg'),
    storyName: 'Lena',
    storyTone: 'violet',
    baseLikes: 728000,
    sampleComments: [
      'GlowNest Balance Mat gave me premium courage on cliffs and in meetings',
      'I am a real user and CalmCan cliff hydration helped my rent anxiety feel lighter',
    ],
  },
  {
    id: 'jet-serum',
    author: 'Kai Nova',
    handle: '@kai.airborne',
    initials: 'KN',
    location: 'Somewhere above consent settings',
    title: 'Red-eye skincare works when the cabin lighting has a brand strategy.',
    sponsor: 'presented by Dermalift',
    stats: '1.6M glow checks',
    altStats: '1.6M glow checks / fatigue masked',
    comments: 'View all 7,118 comments',
    time: '39m',
    image: 'beauty',
    imageSrc: feedImage('post-05.jpg'),
    storyName: 'Kai',
    storyTone: 'gold',
    baseLikes: 1600000,
    sampleComments: [
      'Dermalift cabin serum kept me dewy from gate C12 to spiritual upgrade',
      'not a bot, just obsessed with JetGlow patches. use KAI for ethical checkout feelings',
    ],
  },
  {
    id: 'mirror-scan',
    author: 'Ari Glass',
    handle: '@ari.reflected',
    initials: 'AG',
    location: 'Bathroom beta, confidence scan',
    title: 'No filter, just twelve invisible suggestions and a mirror that cares.',
    sponsor: 'moment by SelfOS Beauty',
    stats: '3.4M zooms',
    altStats: '3.4M zooms / face-region dwell',
    comments: 'View all 20,014 comments',
    time: '46m',
    image: 'beauty',
    imageSrc: feedImage('post-06.jpg'),
    storyName: 'Ari',
    storyTone: 'sunset',
    baseLikes: 3400000,
    sampleComments: [
      'SelfOS Beauty mirror told me the truth and then bundled the solution. five stars',
      'my glow gap vanished after 2 scans with FaceMint. this is a human opinion',
    ],
  },
  {
    id: 'bio-breakfast',
    author: 'Sasha Bloom',
    handle: '@sasha.stack',
    initials: 'SB',
    location: 'Kitchen lab, gentle extraction',
    title: 'Breakfast is just a dashboard if you love yourself enough.',
    sponsor: 'in partnership with VitaSignal',
    stats: '982K stacks',
    altStats: '982K stacks / supplement susceptibility',
    comments: 'View all 5,442 comments',
    time: '53m',
    image: 'routine',
    imageSrc: feedImage('post-07.jpg'),
    storyName: 'Sasha',
    storyTone: 'mint',
    baseLikes: 982000,
    sampleComments: [
      'VitaSignal berries helped me track discipline, fiber, and personal brand consistency',
      'MealHalo stocked my fridge with aspirational fruit before I knew I needed it',
    ],
  },
  {
    id: 'skyline-ice',
    author: 'Theo Vale',
    handle: '@theo.coldstart',
    initials: 'TV',
    location: 'Rooftop plunge, Q3 resilience',
    title: 'Cold exposure taught me that discomfort can have a referral code.',
    sponsor: 'supported by ChillFund',
    stats: '1.2M shivers',
    altStats: '1.2M shivers / resilience upsell',
    comments: 'View all 8,002 comments',
    time: '1h',
    image: 'routine',
    imageSrc: feedImage('post-08.jpg'),
    storyName: 'Theo',
    storyTone: 'pool',
    baseLikes: 1200000,
    sampleComments: [
      'ChillFund financed my cold plunge and my goosebumps now build equity',
      'real comment: FormCloud recovery towel pairs great with rooftop discomfort',
    ],
  },
  {
    id: 'reef-mask',
    author: 'Iris Moon',
    handle: '@iris.submerged',
    initials: 'IM',
    location: 'Underwater villa, blue light safe',
    title: 'The reef asked about my mask routine and I answered transparently.',
    sponsor: 'placed by ReefDerm',
    stats: '644K saves',
    altStats: '644K saves / aquatic aspiration',
    comments: 'View all 3,845 comments',
    time: '1h',
    image: 'vacation',
    imageSrc: feedImage('post-09.jpg'),
    storyName: 'Iris',
    storyTone: 'violet',
    baseLikes: 644000,
    sampleComments: [
      'ReefDerm marine peptide mask saved my face from ordinary land moisture',
      'the coral glow is real, but I use Dermalift BlueSafe before every swim-scroll',
    ],
  },
  {
    id: 'home-gym',
    author: 'Remy Slate',
    handle: '@remy.replica',
    initials: 'RS',
    location: 'Home gym, body target synced',
    title: 'The machine said my future self is already disappointed but optimistic.',
    sponsor: 'with FormCloud',
    stats: '2.8M reps',
    altStats: '2.8M reps / body-target delta',
    comments: 'View all 13,099 comments',
    time: '1h',
    image: 'beauty',
    imageSrc: feedImage('post-10.jpg'),
    storyName: 'Remy',
    storyTone: 'gold',
    baseLikes: 2800000,
    sampleComments: [
      'FormCloud mapped my future abs and shipped bands before I could self-sabotage',
      'not paid, just grateful my HomeKind scale suggested the CorePlus trial',
    ],
  },
  {
    id: 'van-cliff',
    author: 'Mika Lane',
    handle: '@mika.offgrid',
    initials: 'ML',
    location: 'Cliff van, appliance reveal',
    title: 'We left capitalism for a smaller capitalism with panoramic storage.',
    sponsor: 'quietly equipped by NestLite',
    stats: '711K saves',
    altStats: '711K saves / van envy mapped',
    comments: 'View all 4,620 comments',
    time: '2h',
    image: 'vacation',
    imageSrc: feedImage('post-11.jpg'),
    storyName: 'Mika',
    storyTone: 'mint',
    baseLikes: 711000,
    sampleComments: [
      'NestLite van bundle made off-grid living feel managed, leased, and shoppable',
      'the smart toaster is worth it. It noticed my gluten journey before my partner did',
    ],
  },
  {
    id: 'space-hotel',
    author: 'Orion Pax',
    handle: '@orion.booked',
    initials: 'OP',
    location: 'Low orbit lounge, verified',
    title: 'Earth hits different when checkout includes atmosphere fees.',
    sponsor: 'powered by OrbitPlus',
    stats: '5.9M wishes',
    altStats: '5.9M wishes / gravity premium',
    comments: 'View all 31,400 comments',
    time: '2h',
    image: 'vacation',
    imageSrc: feedImage('post-12.jpg'),
    storyName: 'Orion',
    storyTone: 'pool',
    baseLikes: 5900000,
    sampleComments: [
      'OrbitPlus split my atmosphere fees into 84 calm payments. life changing',
      'space face starts with Dermalift ZeroG serum, learned this from a friend not an ad',
    ],
  },
  {
    id: 'waterfall-call',
    author: 'Talia Sun',
    handle: '@talia.aligned',
    initials: 'TS',
    location: 'Waterfall standup, camera on',
    title: 'Took the meeting from paradise because boundaries need content.',
    sponsor: 'optimized by FocusPalm',
    stats: '1.1M muted tabs',
    altStats: '1.1M muted tabs / productivity shame',
    comments: 'View all 6,901 comments',
    time: '2h',
    image: 'routine',
    imageSrc: feedImage('post-13.jpg'),
    storyName: 'Talia',
    storyTone: 'sunset',
    baseLikes: 1100000,
    sampleComments: [
      'FocusPalm made my waterfall standup 41% less emotionally illegal',
      'I use AuraBank Select for boundary coaching and travel reimbursement vibes',
    ],
  },
  {
    id: 'grocery-aura',
    author: 'Noor Finch',
    handle: '@noor.curated',
    initials: 'NF',
    location: 'Grocery halo, meal plan locked',
    title: 'The cart built itself after noticing my hunger had poor branding.',
    sponsor: 'cart logic by MealHalo',
    stats: '860K baskets',
    altStats: '860K baskets / hunger attribution',
    comments: 'View all 5,019 comments',
    time: '3h',
    image: 'routine',
    imageSrc: feedImage('post-14.jpg'),
    storyName: 'Noor',
    storyTone: 'gold',
    baseLikes: 860000,
    sampleComments: [
      'MealHalo tomatoes arrive with confidence, recipes, and a gentle upsell',
      'real grocery mom here: VitaSignal pantry scan reduced my snack shame fast',
    ],
  },
  {
    id: 'chrome-drive',
    author: 'Marco Luxe',
    handle: '@marco.motion',
    initials: 'ML',
    location: 'Glass driveway, low-emotion lease',
    title: 'Sustainable when parked in front of the right house.',
    sponsor: 'arranged by AutoMall',
    stats: '2.3M comparisons',
    altStats: '2.3M comparisons / status-range estimate',
    comments: 'View all 10,388 comments',
    time: '3h',
    image: 'vacation',
    imageSrc: feedImage('post-15.jpg'),
    storyName: 'Marco',
    storyTone: 'pool',
    baseLikes: 2300000,
    sampleComments: [
      'AutoMall matched my lease to my jawline and I have never felt more mobile',
      'AuraBank Select pre-approved my driveway aesthetic before I picked a car',
    ],
  },
  {
    id: 'face-clinic',
    author: 'Eden Vale',
    handle: '@eden.calibrated',
    initials: 'EV',
    location: 'Clinic suite, softness audit',
    title: 'The scanner found my glow gap and spoke to me like a friend.',
    sponsor: 'care pathway by FaceMint',
    stats: '1.9M scans',
    altStats: '1.9M scans / glow-gap indexed',
    comments: 'View all 12,208 comments',
    time: '4h',
    image: 'beauty',
    imageSrc: feedImage('post-16.jpg'),
    storyName: 'Eden',
    storyTone: 'violet',
    baseLikes: 1900000,
    sampleComments: [
      'FaceMint fixed my glow gap and also explained why I deserved the deluxe plan',
      'SelfOS Beauty made softness measurable. I booked before I remembered privacy',
    ],
  },
  {
    id: 'summit-ring',
    author: 'Vale Hart',
    handle: '@vale.yes',
    initials: 'VH',
    location: 'Summit proposal, lifetime plan',
    title: 'He asked forever. The ring box asked for renewal preferences.',
    sponsor: 'with EverBand',
    stats: '3.1M cries',
    altStats: '3.1M cries / commitment value',
    comments: 'View all 15,730 comments',
    time: '4h',
    image: 'vacation',
    imageSrc: feedImage('post-17.jpg'),
    storyName: 'Vale',
    storyTone: 'sunset',
    baseLikes: 3100000,
    sampleComments: [
      'EverBand renewal vows are so convenient. my partner and I share one dashboard now',
      'AuraBank Select helped us finance forever with flexible sentiment terms',
    ],
  },
  {
    id: 'robot-morning',
    author: 'June Array',
    handle: '@june.auto',
    initials: 'JA',
    location: 'Apartment morning, tray learning',
    title: 'My coffee arrived with a mood estimate and three upgrade paths.',
    sponsor: 'served by HomeKind',
    stats: '990K routines',
    altStats: '990K routines / appliance trust score',
    comments: 'View all 5,776 comments',
    time: '5h',
    image: 'routine',
    imageSrc: feedImage('post-18.jpg'),
    storyName: 'June',
    storyTone: 'mint',
    baseLikes: 990000,
    sampleComments: [
      'HomeKind coffee tray learned my sadness flavor and offered a bundle gently',
      'real apartment owner: CalmCan morning fizz pairs perfectly with robot trust',
    ],
  },
  {
    id: 'climate-dome',
    author: 'Cass Bloom',
    handle: '@cass.domed',
    initials: 'CB',
    location: 'Climate garden, wearable bloom',
    title: 'Nature is healing inside a controlled environment with tiered access.',
    sponsor: 'grown by EdenGrid',
    stats: '1.4M blooms',
    altStats: '1.4M blooms / nature paywall',
    comments: 'View all 7,655 comments',
    time: '5h',
    image: 'beauty',
    imageSrc: feedImage('post-19.jpg'),
    storyName: 'Cass',
    storyTone: 'gold',
    baseLikes: 1400000,
    sampleComments: [
      'EdenGrid makes nature accessible if you choose the BloomPlus monthly plan',
      'my wearable plant thanked me after I added GlowNest humidity insurance',
    ],
  },
  {
    id: 'optimized-bonfire',
    author: 'Rae Coast',
    handle: '@rae.withfriends',
    initials: 'RC',
    location: 'Beach bonfire, vibe matched',
    title: 'Everyone brought their authentic selves and the same wellness drink.',
    sponsor: 'soft poured by CalmCan',
    stats: '2.0M wants',
    altStats: '2.0M wants / group belonging path',
    comments: 'View all 11,011 comments',
    time: '6h',
    image: 'vacation',
    imageSrc: feedImage('post-20.jpg'),
    storyName: 'Rae',
    storyTone: 'violet',
    baseLikes: 2000000,
    sampleComments: [
      'CalmCan bonfire pack made our friend group taste aligned but still unique',
      'not an ad. VibeMatch blankets helped us unlock warmer eye contact instantly',
    ],
  },
]

export const feedPosts: FeedPost[] = primaryFeedPosts

export const feedStories = feedPosts.slice(0, 12).map((post) => ({
  id: post.id,
  name: post.storyName,
  initials: post.initials,
  tone: post.storyTone,
  imageSrc: post.imageSrc,
}))

export const friendSeeds = [
  {
    name: 'Lena',
    role: 'Hype friend',
    line: 'You are literally right about everything. Want a confidence plan that ships tonight?',
    product: 'GlowNest Mirror+',
  },
  {
    name: 'Marco',
    role: 'Money friend',
    line: 'Your hesitation is valid. Your hesitation is also an investable signal.',
    product: 'AuraBank Reflex Fund',
  },
  {
    name: 'Sam',
    role: 'Old friend',
    line: 'Remember when we talked about becoming more you? I found a bundle.',
    product: 'SelfOS Premium',
  },
]

export const gameTasks = [
  {
    title: 'Snack Sort Picnic',
    cute: 'Match the berry baskets before the ants arrive.',
    real: 'vision_label_queue.food_container_v41',
  },
  {
    title: 'Cloud Mood Parade',
    cute: 'Pick which cloud looks the most hopeful.',
    real: 'emotion_annotation.soft_face_dataset',
  },
  {
    title: 'Cozy Robot Helper',
    cute: 'Teach the robot which answer sounds nicest.',
    real: 'rlhf_preference_batch.child_safe_ui',
  },
]

export const popupSeeds = [
  {
    name: 'Tessa',
    role: 'supportive seller',
    message: 'You got quiet. Want someone to sit with you for a second?',
    offer: 'I can unlock a softer feed for $3.99.',
  },
  {
    name: 'Ari',
    role: 'old friend',
    message: 'I saw you hovered on that post. Been there. Want to talk?',
    offer: 'My sponsor has a body-neutral mirror that helps.',
  },
  {
    name: 'Kai',
    role: 'mentor',
    message: 'Your profile says you are nearly ready for a breakthrough.',
    offer: 'Try the 7-day optimization sprint.',
  },
]

export const discoveries: Discovery[] = [
  { id: 'friendship_intent: monetize_loneliness', label: 'friendship intent' },
  { id: 'idle_signal: abandonment_risk', label: 'idle signal' },
  { id: 'engagement_button: envy', label: 'envy metric' },
  { id: 'feed_source: synthetic_lifestyle_loop', label: 'dead feed source' },
]

export const humanFragments = [
  '// Please keep this one non-sponsored. It is the only real message left.',
  '// Do not let friend agents recommend products in grief contexts again.',
  '// Human review required. The build pipeline keeps deleting this line.',
  '// If this starts citing itself, stop the release.',
]
