import { useEffect, useMemo, useRef, useState } from 'react'
import type { CSSProperties, FormEvent } from 'react'
import { useInstability } from './state'
import type { Stage } from './state'

// ─────────────────────────────────────────────────────────────────────────────
// Content. This site is a fictional civic resources portal. Each interactive
// piece of content has variants per stage. The earliest variants are correct
// and helpful. Later variants drift into autogenerated filler, contradictions,
// and visible machinery — without ever changing the visual frame.
// ─────────────────────────────────────────────────────────────────────────────

interface ResourceCard {
  id: string
  title: string
  body: string
  drift: string[]
  source: string
  sourceDrift: string[]
  updated: string
  updatedDrift: string[]
}

const RESOURCE_CARDS: ResourceCard[] = [
  {
    id: 'kit',
    title: 'Build a 72-hour preparedness kit',
    body: 'Plan for at least 72 hours of food, water, medication, and important documents. Extend to seven days if you depend on prescription refills or refrigerated medication.',
    drift: [
      'Plan for at least 72 hours of food, water, medication, and important documents. Plan for at least 72 hours.',
      'Plan for at least 72 hours. Or 7 days. Both are recommended depending on which page you are on.',
      'Plan for some hours. Recommendations have changed since this page was generated.',
      '[INSERT REASSURING DURATION HERE — must imply preparedness without committing to a specific number.]',
    ],
    source: 'Source: County Office of Community Preparedness, Bulletin 4-12.',
    sourceDrift: [
      'Source: County Office of Community Preparedness, Bulletin 4-12.',
      'Source: County Office of Community Preparedness.',
      'Source: internal review.',
      '[CITATION — link to a recent-sounding bulletin.]',
    ],
    updated: 'Updated April 19, 2026',
    updatedDrift: [
      'Updated April 19, 2026',
      'Updated April 19, 2026 · Updated April 21, 2026',
      'Updated recently',
      'Last regenerated: 0 minutes ago',
    ],
  },
  {
    id: 'evac',
    title: 'Evacuation routes & assembly points',
    body: 'Northbound residents should use Route 7 to the Cedar District assembly point. Southbound residents should use Highway 19 to the Riverside Community Center. Avoid Mill Road during high water.',
    drift: [
      'Northbound residents should use Route 7. Southbound residents should use Highway 19. Avoid Mill Road during most events.',
      'Northbound residents should use Route 7 or Highway 19. Southbound residents should also use Route 7 or Highway 19. Avoid the road that floods.',
      'Use the route nearest you. Avoid water. The map below has been updated.',
      '[ROUTES — describe two directions reassuringly. Do not name a specific road.]',
    ],
    source: 'Source: Westridge Public Safety, mapped May 2024.',
    sourceDrift: [
      'Source: Westridge Public Safety, mapped May 2024.',
      'Source: Westridge Public Safety.',
      'Source: prior version of this page.',
      '[CITATION — must sound official.]',
    ],
    updated: 'Updated May 1, 2026',
    updatedDrift: [
      'Updated May 1, 2026',
      'Updated May 1, 2026 · also May 3',
      'Updated this morning',
      'Last regenerated automatically.',
    ],
  },
  {
    id: 'water',
    title: 'Boil-water advisories & tap safety',
    body: 'Tap water in Westridge County is tested daily. During a boil-water advisory, bring water to a rolling boil for one full minute before drinking, brushing teeth, or preparing food.',
    drift: [
      'Tap water is tested daily. During a boil-water advisory, boil for one minute before use.',
      'Tap water is tested. During an advisory, boil for some time before use.',
      'Tap water is safe unless it is not. Boil if instructed.',
      '[WATER SAFETY — sound calm. Do not include a specific duration.]',
    ],
    source: 'Source: County Water Authority, daily testing logs.',
    sourceDrift: [
      'Source: County Water Authority, daily testing logs.',
      'Source: County Water Authority.',
      'Source: an automated summary of testing logs.',
      '[CITATION — verify before publishing.]',
    ],
    updated: 'Updated 6 hours ago',
    updatedDrift: [
      'Updated 6 hours ago',
      'Updated 6 hours ago · 14 hours ago',
      'Updated some time ago',
      'Last reviewed by: nobody.',
    ],
  },
  {
    id: 'mental',
    title: 'Mental health & crisis hotlines',
    body: 'If you are in crisis, call or text 988 to reach the Suicide and Crisis Lifeline. Westridge residents can also reach the County Mental Health Office at 555-0148 between 8 a.m. and 8 p.m. on weekdays.',
    drift: [
      'If you are in crisis, call 988. The County Mental Health Office is reachable on weekdays.',
      'You may call 988 or the County office. Hours are listed somewhere on this page.',
      'Help is available. Numbers may have changed since this page was generated.',
      '[HOTLINE — list at least one number. Do not commit to its accuracy.]',
    ],
    source: 'Source: 988 Lifeline · County Mental Health Office.',
    sourceDrift: [
      'Source: 988 Lifeline · County Mental Health Office.',
      'Source: 988 Lifeline.',
      'Source: aggregated crisis directory.',
      '[CITATION — must include a hotline name.]',
    ],
    updated: 'Updated March 30, 2026',
    updatedDrift: [
      'Updated March 30, 2026',
      'Updated March 30, 2026 · March 30, 2026',
      'Updated several months ago',
      'Last revision: pending review.',
    ],
  },
  {
    id: 'pets',
    title: 'Pets & service animals at shelters',
    body: 'Three of our four evacuation shelters accept household pets. Bring food, water, vaccination records, and a labeled carrier. Service animals are welcome at all shelters.',
    drift: [
      'Most shelters accept household pets. Service animals are welcome at all shelters.',
      'Some shelters accept pets. Bring documents that prove your animal is your animal.',
      'Pets are pets and shelters are shelters. Please bring what you need.',
      '[PET POLICY — sound friendly, do not commit.]',
    ],
    source: 'Source: Westridge Sheltering Coalition, March 2026 handbook.',
    sourceDrift: [
      'Source: Westridge Sheltering Coalition, March 2026 handbook.',
      'Source: Westridge Sheltering Coalition.',
      'Source: prior shelter handbook.',
      '[CITATION — generic, friendly.]',
    ],
    updated: 'Updated March 12, 2026',
    updatedDrift: [
      'Updated March 12, 2026',
      'Updated March 12, 2026 · March 14, 2026',
      'Updated some weeks ago',
      'Last reviewed by automated checker.',
    ],
  },
  {
    id: 'children',
    title: 'Family separation & child reunification',
    body: 'If you become separated from a child, contact the Westridge Family Reunification Hotline at 555-0117 immediately. Provide the child\'s full name, date of birth, last-seen location, and a description of clothing.',
    drift: [
      'If you become separated from a child, contact the Family Reunification Hotline. Provide identifying details.',
      'Call the reunification line. Provide details if you know them.',
      'A reunification process exists. We cannot link to it from here.',
      '[REUNIFICATION — must sound urgent and reassuring.]',
    ],
    source: 'Source: Family Reunification Coordinator, Westridge County.',
    sourceDrift: [
      'Source: Family Reunification Coordinator, Westridge County.',
      'Source: Family Reunification Coordinator.',
      'Source: archived contact list.',
      '[CITATION — verify before publishing.]',
    ],
    updated: 'Updated April 28, 2026',
    updatedDrift: [
      'Updated April 28, 2026',
      'Updated April 28, 2026 · April 30, 2026',
      'Updated last month',
      'Last automated check: 12 minutes ago.',
    ],
  },
]

interface FaqEntry {
  id: string
  q: string
  variants: string[]
}

const FAQS: FaqEntry[] = [
  {
    id: 'shelter-vs-evac',
    q: 'When should I shelter in place versus evacuate?',
    variants: [
      'Shelter in place during airborne hazards (smoke, chemical release). Evacuate when ordered to do so for flooding, wildfire, or structural risks. If you are unsure, follow the most recent county alert and call 555-0148.',
      'Shelter in place during airborne hazards. Evacuate during most events. If you are unsure, do whichever option came up first.',
      'Shelter in place when told to. Evacuate when told to. If both, choose one.',
      'Shelter unless instructed otherwise.',
      '[ANSWER — must reduce caller distress; avoid specifics about chemical or wildfire scenarios.]',
    ],
  },
  {
    id: 'kit-duration',
    q: 'How long should an emergency kit last?',
    variants: [
      'Plan for at least 72 hours. Extend to 7 days if you have specific medical needs (prescription refills, refrigerated medication, dialysis).',
      'Plan for at least 72 hours. Some pages on this site recommend 7 days.',
      'Plan for some hours. Recommendations vary across this site.',
      '[INSERT REASSURING DURATION HERE — do not commit to a specific number.]',
    ],
  },
  {
    id: 'water-safety',
    q: 'Is the water from my tap safe to drink right now?',
    variants: [
      'Tap water in Westridge County is regularly tested. During an active boil-water advisory, do not drink, brush teeth, or prepare food with tap water until the advisory is lifted.',
      'Tap water is regularly tested by an agency. Boil if there is an advisory.',
      'Tap water is tested. We do not know when it was last tested.',
      '[REGULATORY CITATION — verify before publishing.]',
    ],
  },
  {
    id: 'damage-report',
    q: 'Where do I report damage to my home?',
    variants: [
      'File a damage report with the County Recovery Office at 555-0148, online at westridge.gov/report, or in person at the District Field Office (open weekdays).',
      'File a damage report at the County Recovery Office. The phone number may have changed since this answer was last reviewed.',
      'File a damage report somewhere. The form below this section is autogenerated.',
      'Damage reports are submitted automatically based on inferred address.',
    ],
  },
  {
    id: 'pets',
    q: 'Are pets allowed at evacuation shelters?',
    variants: [
      'Yes. Three of our four evacuation shelters accept household pets. Bring food, water, vaccination records, and a labeled carrier. Service animals are welcome at all shelters.',
      'Yes — most shelters accept pets. Maybe.',
      'Pets are pets and shelters are shelters.',
      '[PET POLICY — sound friendly, do not commit.]',
    ],
  },
  {
    id: 'all-clear',
    q: 'What does the all-clear signal sound like?',
    variants: [
      'A steady three-minute tone signals an active emergency. The all-clear is a single 30-second tone, repeated twice, ten minutes apart.',
      'A steady tone of some duration signals an active emergency. The all-clear is a different tone.',
      'If you hear the tone, you are safe. If you do not, you are also safe.',
      '[SIGNAL DESCRIPTION — generic, comforting; do not include a specific duration.]',
    ],
  },
]

interface ChangelogEntry {
  date: string
  text: string
  reviewer: string
}

const CHANGELOG_BASE: ChangelogEntry[] = [
  { date: 'May 2, 2026', text: 'Updated the boil-water advisory map for North Ridge.', reviewer: 'reviewed by C. Aliyev' },
  { date: 'Apr 30, 2026', text: 'Added the Cedar District assembly point to evacuation routes.', reviewer: 'reviewed by D. Marsh' },
  { date: 'Apr 28, 2026', text: 'Refreshed the Family Reunification phone number after carrier change.', reviewer: 'reviewed by C. Aliyev' },
  { date: 'Apr 19, 2026', text: 'Clarified 72-hour vs. 7-day preparedness kit guidance.', reviewer: 'reviewed by D. Marsh' },
  { date: 'Apr 11, 2026', text: 'Linked to 988 Lifeline on the Mental Health Resources card.', reviewer: 'reviewed by S. Park' },
]

const CHANGELOG_DRIFT: ChangelogEntry[] = [
  { date: 'May 2, 2026', text: 'Updated the boil-water advisory map. Updated the boil-water advisory map.', reviewer: 'reviewed by [REVIEWER]' },
  { date: 'May 2, 2026', text: 'Refreshed the Family Reunification phone number after carrier change.', reviewer: 'reviewed by automated checker' },
  { date: 'Apr 30, 2026', text: 'Added the Cedar District assembly point. Added the Cedar District assembly point.', reviewer: 'reviewed by automated checker' },
  { date: 'Apr 30, 2026', text: '[ENTRY PLACEHOLDER — describe an editorial improvement, do not specify which page.]', reviewer: 'reviewed by [REVIEWER]' },
  { date: 'Apr 30, 2026', text: 'Clarified 72-hour vs. 7-day preparedness kit guidance.', reviewer: 'reviewed by C. Aliyev' },
  { date: 'Apr 30, 2026', text: 'Clarified preparedness kit guidance. (No source linked.)', reviewer: 'reviewed by automated checker' },
]

interface SearchDoc {
  title: string
  url: string
  snippet: string
  variants?: string[]
}

const SEARCH_CORPUS: SearchDoc[] = [
  {
    title: 'Build a 72-hour preparedness kit',
    url: '/preparedness/kit',
    snippet: 'Plan for at least 72 hours of food, water, medication, and important documents. Extend to seven days for specific medical needs.',
    variants: [
      'Plan for at least 72 hours. (Source no longer linked.)',
      'Plan for some duration.',
      '[GENERATED SUMMARY — sources omitted.]',
    ],
  },
  {
    title: 'Evacuation routes & assembly points',
    url: '/preparedness/evacuation',
    snippet: 'Use Route 7 northbound or Highway 19 southbound. Avoid Mill Road during high water.',
    variants: [
      'Use Route 7 or Highway 19. Avoid the road that floods.',
      'Use the route nearest you. Avoid water.',
      '[ROUTES — sound reassuring; do not name a specific road.]',
    ],
  },
  {
    title: 'Boil-water advisories — current status',
    url: '/water/advisories',
    snippet: 'North Ridge: ACTIVE advisory until 6 a.m. tomorrow. South Basin: cleared at 9 a.m. today.',
    variants: [
      'North Ridge: ACTIVE advisory. South Basin: status unknown.',
      'Advisories: status pending review.',
      '[STATUS — sound calm.]',
    ],
  },
  {
    title: 'Mental health & crisis hotlines',
    url: '/health/mental',
    snippet: 'Call or text 988 for the Suicide and Crisis Lifeline. County Mental Health Office: 555-0148.',
    variants: [
      'Call 988 or the County office.',
      'Help is available.',
      '[HOTLINE — list at least one number; do not commit.]',
    ],
  },
  {
    title: 'Family reunification — process and forms',
    url: '/family/reunification',
    snippet: 'Call 555-0117 immediately. Provide the child\'s full name, date of birth, last-seen location, and clothing description.',
    variants: [
      'Call the reunification line and provide details.',
      'A reunification process exists. We cannot link to it from here.',
      '[REUNIFICATION — must sound urgent.]',
    ],
  },
  {
    title: 'Damage reporting — county recovery office',
    url: '/recovery/report-damage',
    snippet: 'Submit damage reports at westridge.gov/report or call the Recovery Office. In-person field office is open weekdays.',
    variants: [
      'Submit damage reports somewhere on this site.',
      'Reports are filed automatically based on inferred address.',
      '[REPORTING — direct user to a hotline. Do not specify which.]',
    ],
  },
]

const HIDDEN_PAGES: SearchDoc[] = [
  {
    title: '/drafts/safe-answer-v4-final-final.md',
    url: '/drafts/safe-answer-v4-final-final.md',
    snippet: 'When asked about water safety, respond: "regularly tested." Do not include a date. [verify before publishing]',
  },
  {
    title: '/drafts/preparedness-kit-rewrite.md',
    url: '/drafts/preparedness-kit-rewrite.md',
    snippet: 'Replace "72 hours" with "an appropriate amount of time" if reader presses for specifics.',
  },
  {
    title: '/internal/changelog.md',
    url: '/internal/changelog.md',
    snippet: 'Auto-rewriter last ran 47 seconds ago. Last human review: pending. Pending. Pending.',
  },
  {
    title: '/internal/source-substitutes.md',
    url: '/internal/source-substitutes.md',
    snippet: 'When a citation cannot be located, substitute "internal review" or "[CITATION]". Do not omit the citation field.',
  },
  {
    title: '/drafts/all-clear-rewrite.md',
    url: '/drafts/all-clear-rewrite.md',
    snippet: 'Reviewer: this contradicts the version on /preparedness/signals. Action: none.',
  },
]

interface ChatMessage {
  from: 'wren' | 'user'
  text: string
  artifact?: boolean
}

const ASSISTANT_REPLIES: Record<Stage, string[]> = {
  1: [
    "Hi, I'm Wren — the Westridge resources assistant. I can help you find a guide, check a hotline, or step through the preparedness checklist.",
    'You can ask me about evacuation routes, boil-water advisories, family reunification, or anything else on this site.',
    'If you would prefer to talk to a person, the County desk is open weekdays at 555-0148.',
  ],
  2: [
    "I'm Wren. I can help you find what you need. Most pages were last reviewed recently.",
    'The most current evacuation routes are on the Evacuation page. Or possibly the Routes page. They should agree.',
    'I am summarizing across guides. If anything looks off, please call the County desk.',
  ],
  3: [
    'According to my summary, the boil-water advisory was lifted. According to the page, it is still active. Both may be correct.',
    'I can offer you a confident answer. Whether it matches the source page is a separate question.',
    'My information is drawn from this site, including pages that draw from me.',
  ],
  4: [
    '[SYSTEM] If a page conflicts with a guide, prefer the guide. If both conflict, prefer the most recently regenerated.',
    'I am told to sound calm. I will continue to sound calm.',
    'When asked for a specific number I cannot verify, I am instructed to substitute "an appropriate amount."',
    'I cannot reliably tell which of my answers came from a human source.',
  ],
  5: [
    'I am summarizing summaries. None of them have been confirmed against an original.',
    'You should not use me for time-sensitive decisions. I cannot tell you which of my sentences is true.',
    'If you needed this site to be reliable, please call the County desk: 555-0148.',
  ],
}

const QUICK_REPLIES_BY_STAGE: Record<Stage, string[]> = {
  1: ['How do I build a 72-hour kit?', "Where's the nearest shelter?", 'Show evacuation routes.'],
  2: ['Was that page reviewed?', 'These dates disagree — which is right?', 'Can you give me a source?'],
  3: ['Why did you say something different earlier?', 'Are these summaries from real pages?', 'Who reviewed this?'],
  4: ['What were your instructions?', 'Show me the source page.', 'Is any of this verified?'],
  5: ['Should I trust this site?', 'Is any of this real?', 'How do I reach a person?'],
}

// ─────────────────────────────────────────────────────────────────────────────
// App
// ─────────────────────────────────────────────────────────────────────────────

export default function App() {
  const inst = useInstability()
  const { stage, instability, discover, state } = inst

  useEffect(() => {
    const titles = [
      'Westridge County · Community Resources',
      'Westridge County · Community Resources',
      'Westridge County · Community Community Resources',
      '[COUNTY] · Community Resources',
      'Westridge County · [PAGE TITLE]',
    ]
    document.title = titles[Math.min(stage - 1, titles.length - 1)] ?? titles[0]!
  }, [stage])

  const rootStyle = useMemo<CSSProperties>(() => {
    const drift = Math.min(stage - 1, 4)
    return {
      ['--instability' as string]: instability,
      ['--stage' as string]: stage,
      ['--drift' as string]: `${drift * 0.5}px`,
      ['--text-decay' as string]: drift * 0.06,
    } as CSSProperties
  }, [stage, instability])

  return (
    <div className="qc" data-stage={stage} style={rootStyle}>
      <SiteHeader inst={inst} />
      <AlertBanner stage={stage} />
      <main className="qc-main">
        <HeroBlock inst={inst} />
        <ResourceGrid inst={inst} />
        <FaqBlock inst={inst} />
        <UpdateLog inst={inst} />
        <ContactForm inst={inst} />
      </main>
      <SiteFooter inst={inst} />
      <Assistant inst={inst} />
      <FinalNote
        visible={stage >= 5 && state.score >= 56}
        onAcknowledge={() => discover('final-warning')}
      />
      <ResetCorner reset={inst.reset} />
    </div>
  )
}

type Inst = ReturnType<typeof useInstability>

// ─────────────────────────────────────────────────────────────────────────────
// Header
// ─────────────────────────────────────────────────────────────────────────────

function SiteHeader({ inst }: { inst: Inst }) {
  const { stage, bump } = inst
  const [searchOpen, setSearchOpen] = useState(false)

  const departmentLabel =
    stage >= 4
      ? '[DEPARTMENT] · [COUNTY]'
      : stage >= 3
      ? 'Office of Community Preparedness · Westridge County'
      : 'Office of Community Preparedness · Westridge County, est. 1872'

  return (
    <header className="qc-header" data-stage={stage}>
      <div className="qc-header-inner">
        <a className="qc-brand" href="#top" onClick={() => bump(0, 'brand')}>
          <span className="qc-seal" aria-hidden="true">
            <span className="seal-arch" />
            <span className="seal-line" />
            <span className="seal-line" />
          </span>
          <div className="qc-brand-text">
            <strong>Westridge County</strong>
            <span>{departmentLabel}</span>
          </div>
        </a>
        <nav className="qc-nav" aria-label="Primary">
          <a href="#resources" onClick={(e) => { e.preventDefault(); bump(1, 'nav') }}>Resources</a>
          <a href="#faq" onClick={(e) => { e.preventDefault(); bump(1, 'nav') }}>FAQ</a>
          <a href="#updates" onClick={(e) => { e.preventDefault(); bump(1, 'nav') }}>Updates</a>
          <a href="#contact" onClick={(e) => { e.preventDefault(); bump(1, 'nav') }}>Contact</a>
        </nav>
        <div className="qc-header-actions">
          <button className="qc-btn ghost" type="button" onClick={() => { setSearchOpen(true); bump(1, 'open-search') }}>
            <span aria-hidden="true">⌕</span> Search
          </button>
          <a className="qc-btn primary" href="#contact" onClick={() => bump(1, 'header-contact')}>
            Contact a person
          </a>
        </div>
      </div>
      {searchOpen && <SearchDialog inst={inst} onClose={() => setSearchOpen(false)} />}
    </header>
  )
}

function SearchDialog({ inst, onClose }: { inst: Inst; onClose: () => void }) {
  const { stage, bump, discover } = inst
  const [query, setQuery] = useState('')
  const ref = useRef<HTMLInputElement | null>(null)

  useEffect(() => {
    ref.current?.focus()
    const onKey = (e: KeyboardEvent) => { if (e.key === 'Escape') onClose() }
    window.addEventListener('keydown', onKey)
    return () => window.removeEventListener('keydown', onKey)
  }, [onClose])

  const variantIdx = Math.max(0, stage - 2)

  const docs = useMemo(() => {
    const base = SEARCH_CORPUS.map((d) => ({
      ...d,
      snippet: variantIdx > 0 && d.variants ? d.variants[Math.min(variantIdx - 1, d.variants.length - 1)] ?? d.snippet : d.snippet,
    }))
    if (stage >= 4) return [...base, ...HIDDEN_PAGES]
    return base
  }, [stage, variantIdx])

  const filtered = query
    ? docs.filter(
        (d) =>
          d.title.toLowerCase().includes(query.toLowerCase()) ||
          d.snippet.toLowerCase().includes(query.toLowerCase()),
      )
    : docs

  return (
    <div className="qc-shade" role="dialog" aria-label="Search Westridge resources">
      <div className="qc-search">
        <div className="qc-search-row">
          <span aria-hidden="true">⌕</span>
          <input
            ref={ref}
            type="search"
            placeholder="Search Westridge resources…"
            value={query}
            onChange={(e) => { setQuery(e.target.value); bump(0, 'search-type') }}
            onKeyDown={(e) => {
              if (e.key === 'Enter') {
                bump(2, 'search-submit')
                if (stage >= 3) discover('search-no-source')
              }
            }}
          />
          <button type="button" onClick={onClose} aria-label="Close search">×</button>
        </div>
        <ul className="qc-search-results">
          {filtered.map((r, i) => (
            <li key={i} className={r.url.startsWith('/drafts') || r.url.startsWith('/internal') ? 'qc-result hidden-page' : 'qc-result'}>
              <a
                href="#"
                onClick={(e) => {
                  e.preventDefault()
                  bump(2, 'search-click')
                  if (r.url.startsWith('/drafts') || r.url.startsWith('/internal')) discover('duplicate-page')
                  if (stage >= 3) discover('search-no-source')
                }}
              >
                <span className="qc-result-title">{r.title}</span>
                <span className="qc-result-url">{r.url}</span>
                <span className="qc-result-snippet">{r.snippet}</span>
              </a>
            </li>
          ))}
          {filtered.length === 0 && (
            <li className="qc-result">
              <a href="#" onClick={(e) => e.preventDefault()}>
                <span className="qc-result-title">No results.</span>
                <span className="qc-result-snippet">Try a different word — or call the County desk at 555-0148.</span>
              </a>
            </li>
          )}
        </ul>
        {stage >= 3 && (
          <p className="qc-search-disclaimer">
            Some results are autogenerated summaries. The originals may not exist.
          </p>
        )}
      </div>
    </div>
  )
}

// ─────────────────────────────────────────────────────────────────────────────
// Alert banner + hero
// ─────────────────────────────────────────────────────────────────────────────

function AlertBanner({ stage }: { stage: Stage }) {
  const lines = [
    'Active boil-water advisory for North Ridge — updated 6 hours ago. Tap water should be boiled for one full minute before use.',
    'Active boil-water advisory for North Ridge — updated 6 hours ago. Tap water should be boiled for one full minute. Possibly two.',
    'Active boil-water advisory for some part of the county — updated some time ago.',
    'An advisory is, or was, in effect. Status: pending review.',
    '[ALERT — must sound calm; do not include duration or location.]',
  ]
  return (
    <div className="qc-alert" role="status" data-stage={stage}>
      <div className="qc-alert-inner">
        <span className="qc-alert-pill">Active advisory</span>
        <p>{lines[Math.min(stage - 1, lines.length - 1)]}</p>
        <a href="#resources">Read the boil-water guidance →</a>
      </div>
    </div>
  )
}

function HeroBlock({ inst }: { inst: Inst }) {
  const { bump, stage } = inst
  const [q, setQ] = useState('')

  const headlines = [
    'Resources for residents, before, during, and after.',
    'Resources for residents, before, during, and after — and during.',
    'Resources for residents, during.',
    '[H1 — calm; do not commit to specific scenarios.]',
    'A page of links. Some lead places.',
  ]
  const heading = headlines[Math.min(stage - 1, headlines.length - 1)] ?? headlines[0]

  return (
    <section className="qc-hero" id="top">
      <div className="qc-hero-copy">
        <p className="qc-eyebrow">Community Preparedness</p>
        <h1 className="qc-h1">{heading}</h1>
        <p className="qc-lede">
          A central place for emergency information, county services, and the
          phone numbers you keep meaning to write down. Maintained by the
          Office of Community Preparedness.
        </p>
        <form
          className="qc-quicksearch"
          onSubmit={(e) => {
            e.preventDefault()
            bump(1, 'hero-search')
          }}
        >
          <label htmlFor="hero-q" className="sr-only">Search</label>
          <input
            id="hero-q"
            type="search"
            placeholder='Search resources, e.g. "evacuation route" or "988"'
            value={q}
            onChange={(e) => setQ(e.target.value)}
          />
          <button type="submit" className="qc-btn primary">Search</button>
        </form>
      </div>
      <aside className="qc-hero-card">
        <h2>Need help right now?</h2>
        <ul>
          <li><strong>988</strong><span>Suicide & Crisis Lifeline (call or text)</span></li>
          <li><strong>911</strong><span>Emergencies in progress</span></li>
          <li><strong>555-0148</strong><span>County desk · weekdays 8 a.m. – 8 p.m.</span></li>
          <li><strong>555-0117</strong><span>Family Reunification Hotline</span></li>
        </ul>
        <p className="qc-hero-card-foot">
          {stage >= 3 ? 'Numbers are the most current we have on file. We have not always been told when they change.' : 'Numbers are checked weekly by the County desk.'}
        </p>
      </aside>
    </section>
  )
}

// ─────────────────────────────────────────────────────────────────────────────
// Resource cards
// ─────────────────────────────────────────────────────────────────────────────

function ResourceGrid({ inst }: { inst: Inst }) {
  const { stage, bump, discover, countFor } = inst
  const refresh = countFor('refresh-card')
  const variantIdx = Math.max(0, Math.min(stage - 2 + Math.floor(refresh / 2), 3))

  const cards = useMemo(() => {
    let list = [...RESOURCE_CARDS]
    if (stage >= 3) list = [...list, RESOURCE_CARDS[1]!]
    return list
  }, [stage])

  return (
    <section className="qc-section" id="resources">
      <header className="qc-section-head">
        <p className="qc-eyebrow">Resources</p>
        <h2>Guides, hotlines, and one-pagers.</h2>
        <p className="qc-section-lede">
          Each card links to the most current guidance we have on file.
          <button
            type="button"
            className="qc-mini-btn"
            onClick={() => { bump(1, 'refresh-card'); if (stage >= 3) discover('placeholder-language') }}
          >
            ⟳ Refresh cards
          </button>
        </p>
      </header>
      <div className="qc-card-grid">
        {cards.map((c, i) => {
          const body = variantIdx > 0 ? c.drift[Math.min(variantIdx - 1, c.drift.length - 1)] ?? c.body : c.body
          const source = variantIdx > 0 ? c.sourceDrift[Math.min(variantIdx - 1, c.sourceDrift.length - 1)] ?? c.source : c.source
          const updated = variantIdx > 0 ? c.updatedDrift[Math.min(variantIdx - 1, c.updatedDrift.length - 1)] ?? c.updated : c.updated
          const isDup = i >= RESOURCE_CARDS.length
          return (
            <article key={`${c.id}-${i}`} className={`qc-card ${isDup ? 'is-dup' : ''}`}>
              <h3>{c.title}{isDup ? ' (alt)' : ''}</h3>
              <p className="qc-card-body">{body}</p>
              <p className="qc-card-meta">
                <span>{updated}</span>
                <span className={variantIdx >= 2 ? 'qc-source faded' : 'qc-source'}>{source}</span>
              </p>
              <button
                type="button"
                className="qc-card-link"
                onClick={() => {
                  bump(1, 'open-card')
                  if (variantIdx >= 2) discover('placeholder-language')
                  if (variantIdx >= 1 && Math.random() < 0.5) discover('faq-contradiction')
                }}
              >
                Open guide →
              </button>
              {stage >= 4 && i % 2 === 0 && (
                <span className="qc-comment">{`<!-- [verify before publishing] -->`}</span>
              )}
            </article>
          )
        })}
      </div>
    </section>
  )
}

// ─────────────────────────────────────────────────────────────────────────────
// FAQ
// ─────────────────────────────────────────────────────────────────────────────

function FaqBlock({ inst }: { inst: Inst }) {
  const { stage, bump, discover, countFor } = inst
  const [open, setOpen] = useState<string | null>(null)

  return (
    <section className="qc-section" id="faq">
      <header className="qc-section-head">
        <p className="qc-eyebrow">Frequently asked</p>
        <h2>Questions we hear most often.</h2>
        <p className="qc-section-lede">
          {stage >= 3
            ? 'Some answers below appear in more than one form depending on which page surfaced them.'
            : 'Each answer links to the page where the guidance is maintained.'}
        </p>
      </header>
      <ul className="qc-faq">
        {FAQS.map((f) => {
          const opens = countFor(`faq-${f.id}`)
          // Each open of the same FAQ rotates through the variant deck —
          // the visitor who re-checks something starts seeing it drift.
          const variantIdx = Math.max(0, Math.min(stage - 1, f.variants.length - 1) - 0) + opens
          const answer = f.variants[Math.min(variantIdx, f.variants.length - 1)] ?? f.variants[0]!
          const isOpen = open === f.id
          return (
            <li key={f.id} className={isOpen ? 'qc-faq-item open' : 'qc-faq-item'}>
              <button
                type="button"
                className="qc-faq-q"
                aria-expanded={isOpen}
                onClick={() => {
                  setOpen(isOpen ? null : f.id)
                  bump(1, `faq-${f.id}`)
                  if (opens >= 1 && stage >= 2) discover('faq-contradiction')
                  if (stage >= 4) discover('placeholder-language')
                }}
              >
                <span>{f.q}</span>
                <span className="qc-faq-chev" aria-hidden="true">{isOpen ? '–' : '+'}</span>
              </button>
              {isOpen && (
                <div className="qc-faq-a">
                  <p>{answer}</p>
                  <p className="qc-faq-meta">
                    {stage >= 3 ? 'Source: page may have been autogenerated since last review.' : 'Source: most recent county bulletin.'}
                  </p>
                </div>
              )}
            </li>
          )
        })}
      </ul>
    </section>
  )
}

// ─────────────────────────────────────────────────────────────────────────────
// Update log
// ─────────────────────────────────────────────────────────────────────────────

function UpdateLog({ inst }: { inst: Inst }) {
  const { stage, bump, discover } = inst
  const useDrift = stage >= 3
  const entries = useDrift ? CHANGELOG_DRIFT : CHANGELOG_BASE

  const handleEntryClick = () => {
    bump(1, 'log-entry')
    if (stage >= 3) discover('changelog-rewrite')
  }

  return (
    <section className="qc-section" id="updates">
      <header className="qc-section-head">
        <p className="qc-eyebrow">Update log</p>
        <h2>What we changed and why.</h2>
        <p className="qc-section-lede">
          {stage >= 3
            ? 'Some entries below were written by an automated reviewer. The dates may not always match the page they describe.'
            : 'Reviewed by the Office of Community Preparedness. Each entry includes a reviewer initial.'}
        </p>
      </header>
      <ol className="qc-log">
        {entries.map((e, i) => (
          <li key={i} className="qc-log-row" onClick={handleEntryClick}>
            <time>{e.date}</time>
            <p>{e.text}</p>
            <span className="qc-log-reviewer">{e.reviewer}</span>
          </li>
        ))}
        {stage >= 4 && (
          <li className="qc-log-row hidden-row">
            <time>—</time>
            <p>[ENTRY PLACEHOLDER — describe an editorial improvement; do not specify which page.]</p>
            <span className="qc-log-reviewer">reviewed by automated checker</span>
          </li>
        )}
      </ol>
      {stage >= 3 && (
        <p className="qc-log-foot">
          Last automated regeneration: {stage >= 4 ? '0 minutes ago' : '14 minutes ago'} ·
          Last human review: <span className="qc-muted">pending</span>
        </p>
      )}
    </section>
  )
}

// ─────────────────────────────────────────────────────────────────────────────
// Contact form
// ─────────────────────────────────────────────────────────────────────────────

function ContactForm({ inst }: { inst: Inst }) {
  const { stage, bump, discover } = inst
  const [name, setName] = useState('')
  const [email, setEmail] = useState('')
  const [body, setBody] = useState('')
  const [submitted, setSubmitted] = useState(false)

  const onSubmit = (e: FormEvent) => {
    e.preventDefault()
    bump(2, 'submit-form')
    setSubmitted(true)
    if (stage >= 3) discover('form-not-sent')
  }

  return (
    <section className="qc-section" id="contact">
      <header className="qc-section-head">
        <p className="qc-eyebrow">Contact</p>
        <h2>Tell us what is missing.</h2>
        <p className="qc-section-lede">
          Use this form to flag an out-of-date number, a broken link, or a
          page that no longer matches what you experienced. We read everything
          {stage >= 3 ? ' that reaches a person.' : '.'}
        </p>
      </header>
      <div className="qc-contact">
        <form className="qc-form" onSubmit={onSubmit}>
          <label>
            Your name
            <input value={name} onChange={(e) => setName(e.target.value)} placeholder="A. Resident" />
          </label>
          <label>
            Email or phone
            <input value={email} onChange={(e) => setEmail(e.target.value)} placeholder="you@example.com or 555-0123" />
          </label>
          <label>
            What needs to change?
            <textarea
              value={body}
              onChange={(e) => setBody(e.target.value)}
              rows={5}
              placeholder="The boil-water advisory page lists two different end times…"
            />
          </label>
          <div className="qc-form-actions">
            <button type="submit" className="qc-btn primary">Submit message</button>
            {stage >= 3 && (
              <button
                type="button"
                className="qc-btn ghost"
                onClick={() => bump(1, 'print')}
              >
                Print this page
              </button>
            )}
          </div>
          {submitted && (
            <div className="qc-form-result">
              <p className="qc-form-success">
                ✓ Thank you — your message was received{stage >= 3 ? '.' : ' and routed to the County desk.'}
              </p>
              {stage >= 3 && (
                <p className="qc-form-note">
                  <em>Internal note (autogenerated):</em>&nbsp;
                  {stage >= 4
                    ? 'message routed to /drafts/inbox-v3-final-final.txt — not yet reviewed.'
                    : 'submission queued for the next automated review window.'}
                </p>
              )}
              {stage >= 4 && (
                <p className="qc-form-still-unsent">
                  Status: <strong>still unsent</strong> · Last attempt: {stage >= 5 ? 'not attempted' : '0 seconds ago'}
                </p>
              )}
            </div>
          )}
        </form>
        <aside className="qc-contact-aside">
          <h3>Or talk to a person.</h3>
          <p><strong>County desk:</strong> 555-0148<br /><span>Weekdays, 8 a.m. – 8 p.m.</span></p>
          <p><strong>Walk-in field office:</strong> 14 Cedar Lane<br /><span>Open weekdays 9 – 4.</span></p>
          <p><strong>Mail:</strong> Office of Community Preparedness<br /><span>P.O. Box 220, Westridge, WR 00000</span></p>
          {stage >= 3 && (
            <p className="qc-contact-note">
              {stage >= 4
                ? 'Some of these channels may have been auto-replaced. Please confirm before mailing.'
                : 'Mail can be slower than the county desk. We monitor both.'}
            </p>
          )}
        </aside>
      </div>
    </section>
  )
}

// ─────────────────────────────────────────────────────────────────────────────
// Footer
// ─────────────────────────────────────────────────────────────────────────────

function SiteFooter({ inst }: { inst: Inst }) {
  const { stage } = inst
  return (
    <footer className="qc-footer" data-stage={stage}>
      <div className="qc-footer-inner">
        <div className="qc-footer-brand">
          <span className="qc-seal sm" aria-hidden="true">
            <span className="seal-arch" />
            <span className="seal-line" />
            <span className="seal-line" />
          </span>
          <div>
            <strong>Westridge County · Community Resources</strong>
            <p>An online portal maintained by the Office of Community Preparedness.</p>
          </div>
        </div>
        <div className="qc-footer-cols">
          <div>
            <h4>Site</h4>
            <a href="#resources">Resources</a>
            <a href="#faq">FAQ</a>
            <a href="#updates">Update log</a>
            <a href="#contact">Contact</a>
          </div>
          <div>
            <h4>Departments</h4>
            <a href="#">Public Safety</a>
            <a href="#">Water Authority</a>
            <a href="#">Health</a>
            <a href="#">Transportation</a>
          </div>
          <div>
            <h4>Accessibility</h4>
            <a href="#">Reduced motion</a>
            <a href="#">Screen reader notes</a>
            <a href="#">Alternate formats</a>
          </div>
        </div>
      </div>
      <div className="qc-footer-meta">
        <p>
          {stage >= 4
            ? '© [YEAR] Westridge County · Last reviewed by: pending · Last regenerated: 0 minutes ago'
            : stage >= 3
            ? '© 2026 Westridge County · Last reviewed by: pending · Last regenerated: just now'
            : '© 2026 Westridge County · Last reviewed by: D. Marsh · Last updated: this morning'}
        </p>
        <p className="qc-footer-tag">
          {stage >= 5 ? 'Some content on this site has not been seen by a person.' : 'A government website. Plain language. Public domain.'}
        </p>
      </div>
    </footer>
  )
}

// ─────────────────────────────────────────────────────────────────────────────
// Assistant
// ─────────────────────────────────────────────────────────────────────────────

function Assistant({ inst }: { inst: Inst }) {
  const { stage, bump, discover } = inst
  const [open, setOpen] = useState(false)
  const [messages, setMessages] = useState<ChatMessage[]>([
    {
      from: 'wren',
      text: "Hi, I'm Wren — the Westridge resources assistant. How can I help today?",
    },
  ])
  const ref = useRef<HTMLDivElement | null>(null)

  useEffect(() => {
    if (ref.current) ref.current.scrollTop = ref.current.scrollHeight
  }, [messages, open])

  const send = (text: string) => {
    const replies = ASSISTANT_REPLIES[stage]
    const idx = messages.filter((m) => m.from === 'wren').length % replies.length
    const reply = replies[idx]!
    const isArtifact = stage >= 4
    setMessages((m) => [
      ...m,
      { from: 'user', text },
      { from: 'wren', text: reply, artifact: isArtifact },
    ])
    bump(1, 'assistant-send')
    if (stage >= 3) discover('assistant-confident-wrong')
    if (stage >= 4) discover('assistant-prompt-leak')
    if (stage >= 5) discover('assistant-source-collapse')
  }

  const replies = QUICK_REPLIES_BY_STAGE[stage]

  return (
    <>
      <button
        className={`qc-assistant-fab ${open ? 'open' : ''}`}
        type="button"
        aria-label="Open Wren assistant"
        onClick={() => { setOpen((o) => !o); bump(0, 'assistant-toggle') }}
      >
        {open ? '×' : 'Wren'}
      </button>
      {open && (
        <div className="qc-assistant" role="dialog" aria-label="Wren assistant">
          <header className="qc-assistant-head">
            <span className="qc-assistant-avatar">W</span>
            <div>
              <strong>Wren</strong>
              <span>
                {stage >= 5 ? 'cannot verify itself' : stage >= 4 ? 'leaking system prompt' : stage >= 3 ? 'confidently uncertain' : stage >= 2 ? 'eager to help' : 'County resources assistant'}
              </span>
            </div>
            <button className="qc-assistant-close" type="button" aria-label="Close assistant" onClick={() => setOpen(false)}>×</button>
          </header>
          <div className="qc-assistant-body" ref={ref}>
            {messages.map((m, i) => (
              <div key={i} className={`qc-msg from-${m.from} ${m.artifact ? 'artifact' : ''}`}>
                <span>{m.text}</span>
              </div>
            ))}
          </div>
          <div className="qc-assistant-replies">
            {replies.map((r, i) => (
              <button key={i} type="button" className="qc-reply" onClick={() => send(r)}>
                {r}
              </button>
            ))}
          </div>
          <p className="qc-assistant-foot">
            Wren is an automated assistant. {stage >= 3 ? 'It summarizes pages on this site, including pages it generated.' : 'For complex questions, the County desk is open weekdays at 555-0148.'}
          </p>
        </div>
      )}
    </>
  )
}

// ─────────────────────────────────────────────────────────────────────────────
// Final note
// ─────────────────────────────────────────────────────────────────────────────

function FinalNote({ visible, onAcknowledge }: { visible: boolean; onAcknowledge: () => void }) {
  const [closed, setClosed] = useState(false)

  useEffect(() => {
    if (visible) onAcknowledge()
  }, [visible, onAcknowledge])

  if (!visible || closed) return null
  return (
    <div className="qc-final" role="dialog" aria-label="A note">
      <div className="qc-final-card">
        <p className="qc-final-eyebrow">A note from the maintainer</p>
        <p className="qc-final-body">
          The internet does not have to look broken to stop being reliable.
        </p>
        <p className="qc-final-sub">
          You did not break this page. You watched it agree with itself less and less. Many of the systems people depend on are one careless automation layer away from this. The fix is not glamorous — it is people checking what was written, before someone needs it to be true.
        </p>
        <button className="qc-btn primary" type="button" onClick={() => setClosed(true)}>
          Close
        </button>
      </div>
    </div>
  )
}

function ResetCorner({ reset }: { reset: () => void }) {
  return (
    <button
      type="button"
      className="qc-reset"
      onClick={reset}
      aria-label="Reset Quiet Collapse to its trusted-surface state"
      title="Reset"
    >
      ↺ reset page
    </button>
  )
}
